### ISSUE TITLE
Place released version 0.2.x into Maven Repository.

### ISSUE THREAD

**Issue by JeneJasper** [SonarQubeCommunity/sonar-maven-report#9] opened 2018-01-17 20:23 UTC
Tried running:

mvn release:prepare -DpushChanges=false 

Which created 'maven-report-0.2' tag.

But when running:

mvn release:perform.

This failed thus could only pushed release plugin commits to GitHub.

**Comment by JeneJasper** [comment] 2018-01-17 20:25
See also https://github.com/SonarQubeCommunity/sonar-maven-report/issues/6#issuecomment-358162272

**Comment by simonbrandhof** [comment] 2018-01-18 08:09
The problem is that the single version 0.1 has been released in 2009 ! The groupId org.codehaus.sonar-plugins is no more valid, the Codehaus foundation closed a few years ago. 
A solution is to change the groupId and to request for deployment to Sonatype: http://central.sonatype.org/pages/ossrh-guide.html. 
WDYT ?

**Comment by JeneJasper** [comment] 2018-01-18 16:46
I know OSSRH which I use for my own GitLab [projects](https://gitlab.com/freedumbytes/setup). But I don't know how strict they are about owning the site related the groupId. Thus what would be a good groupId?

After reading up on their documentation. 

Do you already have an account for [OSSRH](http://central.sonatype.org/pages/ossrh-guide.html) ? Otherwise [signup](https://issues.sonatype.org/secure/Signup!default.jspa) to create an issue to [Claim Your Namespace](https://issues.sonatype.org/secure/CreateIssue.jspa?issuetype=21&pid=10134).

With for example based on their [video](https://www.youtube.com/watch?v=0gyF17kWMLg):

- Group Id: com.github.sonarqubecommunity
- Project URL: https://github.com/SonarQubeCommunity
- SCM url: https://github.com/SonarQubeCommunity
- Username(s): simonbrandhof jenejasper

After about one day it should be possible to deploy to OSSRH and thus sync to Maven.

After setting up [PGP Signatures](https://freedumbytes.gitlab.io/dpl/html/complete-manual.html#prj.maven.deploy.pgp) and the [Nexus Staging plugin](https://freedumbytes.gitlab.io/dpl/html/complete-manual.html#prj.maven.deploy.artifact.open.source) I should be able to mvn deploy to OSSRH with my account configured in [settings.xml](https://freedumbytes.gitlab.io/dpl/html/complete-manual.html#repo.nexus.maven.distribution.management).

**Note**: I dont know is this applies - 

> Lastly, if your component is already in Central be sure to note this in your ticket, and review how to migrate to [OSSRH](http://central.sonatype.org/articles/2014/Feb/27/migrating-a-project-to-ossrh)

**Comment by JeneJasper** [comment] 2018-01-20 00:14
Other groupId options, which would be more specific for this project and thus also only this project/scm url::

- com.github.sonarqubecommunity.maven.plugins.report
- com.github.sonarqube.community.maven.plugins.report
- com.github.sonarqube.maven.plugins.report

Or alternatively, and maybe with less hassle, create a fork of the current project master, which is then
released under the groupId I'm already using, as for example:

```
  <groupId>nl.demon.shadowland.maven.plugins.sonarqube</groupId>
  <artifactId>sonarqube-maven-report</artifactId>
  <packaging>maven-plugin</packaging>
  <version>0.2.0-SNAPSHOT</version>
```

**Comment by simonbrandhof** [comment] 2018-01-21 13:41
+1 for the last option. It sounds the simplest one.

**Closed as completed** 2018-01-26 00:38 UTC
